name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Zip release
        run: zip -r hardcoverapp.koplugin.zip . -x '*.git*' 'spec/*' 'lua_modules/*' '.luarocks/*' 'lua' 'luarocks' '.tool-versions'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: hardcoverapp.koplugin.zip
